sudo: false
language: php

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update

services:
  - elasticsearch

install:
  - composer install

before_script:
  - sleep 5

before_script:
  - mkdir -p build/logs

script:
  - export ELASTICSEARCH_ROOT_VERSION=2 && phpunit --coverage-clover build/logs/clover.xml
  - export ELASTICSEARCH_ROOT_VERSION=5 && phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'